version: '2'
services:
    mongo:
      container_name: gtfsrt_mongo_store
      image: mongo
      ports:
        - "27017:27017"
      volumes:
        - ./mongo_data:/data/db
        - ./shared:/shared/
      command: mongod --auth
